//
// Created by brok1n on 16-4-28.
//

#ifndef THECPROGRAMMINGLANGUAGESECOONDEDITION_HEADER_H
#define THECPROGRAMMINGLANGUAGESECOONDEDITION_HEADER_H


int submain(void);

#endif //THECPROGRAMMINGLANGUAGESECOONDEDITION_HEADER_H
